In [2]:
import tensorflow as tf

2024-08-07 14:19:50.949265: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-07 14:19:50.952856: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-07 14:19:50.962458: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-07 14:19:50.980081: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-07 14:19:50.985088: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-07 14:19:50.998207: I tensorflow/core/platform/cpu_feature_gu

In [1]:
from sklearn.preprocessing import MinMaxScaler

In [2]:
a = MinMaxScaler()

'MinMaxScaler()'

In [88]:
matrix = tf.constant([
    [0,0],
    [1,2],
    [3,4],
    [0,6],
    [7,8],
    [0,0],
], dtype=tf.float32)
matrix

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[0., 0.],
       [1., 2.],
       [3., 4.],
       [0., 6.],
       [7., 8.],
       [0., 0.]], dtype=float32)>

In [91]:
mask = tf.less_equal(matrix[:, 0], 0)
mask

<tf.Tensor: shape=(6,), dtype=bool, numpy=array([ True, False, False,  True, False,  True])>

In [92]:
filtered_tensor= tf.boolean_mask(matrix, mask)
filtered_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 6.],
       [0., 0.]], dtype=float32)>

In [82]:
=====================================

SyntaxError: invalid syntax (609749174.py, line 1)

In [28]:
# Create a boolean mask where the first element of each row is not zero
mask = tf.not_equal(matrix, 0)

# Apply the mask to select rows
filtered_tensor = tf.boolean_mask(matrix, mask)
filtered_tensor[:-1]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [29]:
filtered_tensor_roll = tf.roll(filtered_tensor, shift=-1, axis=0)
filtered_tensor_roll[:-1]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [30]:
difference =  - 
difference

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>

In [36]:
#call filtered_tensor > filtered_tensor_roll
difference = tf.maximum( filtered_tensor_roll[:-1],filtered_tensor[:-1] , 0.0)
difference

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [35]:
#put filtered_tensor_roll > filtered_tensor
difference = tf.maximum( filtered_tensor[:-1] - filtered_tensor_roll[:-1] , 0.0)
difference

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>